<!DOCTYPE strongsdictionary [
   <!ELEMENT strongsdictionary (prologue, entries) >
   <!ELEMENT prologue (#PCDATA) >
   <!ELEMENT entries (entry)+ >
   <!ELEMENT entry (#PCDATA|strongs|greek|pronunciation|latin|strongsref|strongs_def|strongs_derivation|kjv_def)* >
   <!ATTLIST entry strongs CDATA #REQUIRED >
   <!ELEMENT greek EMPTY >


   <!-- unicode is real Greek. translit is SBL-style transliteration. -->
   <!ATTLIST greek BETA CDATA #REQUIRED 
                   unicode CDATA #REQUIRED 
                   translit CDATA #REQUIRED >
   <!ELEMENT latin (#PCDATA) >
   <!ELEMENT kjv_def (#PCDATA|strongsref)* >
   <!ELEMENT strongs_def (#PCDATA|greek|latin|strongsref|pronunciation)* >
   <!ELEMENT strongs_derivation (#PCDATA|greek|latin|strongsref|pronunciation)* >
   <!ELEMENT pronunciation EMPTY >
   <!ATTLIST pronunciation strongs CDATA #REQUIRED >
   <!ELEMENT strongs (#PCDATA) >
   <!ELEMENT strongsref EMPTY >
   <!ATTLIST strongsref language (GREEK|HEBREW) #REQUIRED
                 strongs CDATA #REQUIRED >
 ]>
<strongsdictionary>
  <prologue>
                     Dictionary of Greek Words
			      taken from
                   Strong's Exhaustive Concordance
                                  by
                     James Strong, S.T.D., LL.D.
                                 1890

                     Public Domain -- Copy Freely

XML e-text version
==================

The XML version of this work was prepared in 2006 by Ulrik
Sandborg-Petersen (http://ulrikp.org) from the ASCII e-text version
presented below.  The XML version contains "real" UTF-8 Greek where
the original ASCII e-text version had transliteration.  The XML has a
stand-alone DTD which should be easy to follow.

Ulrik Sandborg-Petersen welcomes bugfixes to the text.  Please send
them to the address provided on the website:

http://ulrikp.org


Ulrik Sandborg-Petersen



     -------------- original announcement follows --------------


                Dictionaries of Hebrew and Greek Words
                              taken from
                   Strong's Exhaustive Concordance
                                  by
                     James Strong, S.T.D., LL.D.
                                 1890

                     Public Domain -- Copy Freely

For a hundred years Strong's Dictionaries have been popular with Bible
students.  By assigning numbers to each unique word in the Old and New
Testaments and listing each word with its number, Strong produced a
standard, still used today, for referencing definitions. Bible
students, with little or no knowledge of Greek and Hebrew, are able to
use Strong's numbers to learn about the Greek and Hebrew of the Bible.

ASCII e-text version:
=====================

The files for this e-text were produced by Michael Grier,
mgrier@pdnt.com, in 1996, and download from
http://members.tripod.com/~SoftIdeas, in February 1998. The files have
been setup for importing into the Online Bible for DOS. But to make
these files into generic text files, all that is needed is to replace
the terms "GREEK" and "HEBREW" with "Greek" and "Hebrew" or the names
of the appropriate files.

The e-text has been changed from the printed version in three ways.

1) A five digit Strong's word number with leading zeros has been placed before
   each entry. 
2) Where Strong provides the number of another word for etymology,
   a line with "see GREEK for" or "see HEBREW for" and the number, has been
   added after Strong's entry for the word. (This is for use after
   importing into the DOS version of Online Bible, but also provides a good
   way to programmatically add links.)
3) The abbreviations used by Strong in the
   Greek dictionary, (not Hebrew) have been replaced by the abbreviated words.

Michael Grier did a check of the e-text against a printed Strong's
dictionary.  The work seems clean but more proofreading is needed to
certify it clean from errors.

Further info:
=============

If you are looking for Strong's that will self install into the Online
Bible see:
           Michael Grier
           mgrier@pdnt.com
           http://members.tripod.com/~SoftIdeas

If any errors are located, please ensure you have the latest files,
and if so, we would appreciate being informed of the error.

           Bible Foundation
           bf@bf.org
           http://www.bf.org/
           or the e-text Library
           http://www.bf.org/bfetexts.htm

</prologue>
  <entries>
    <entry strongs="00001">
      <strongs>1</strongs>
      <greek BETA="*A" unicode="?" translit="A" />
      <pronunciation strongs="al'-fah" />
      <strongs_derivation>of Hebrew origin;</strongs_derivation>
      <strongs_def> the first letter of the alphabet; figuratively, only
 (from its use as a numeral) the first: </strongs_def>
      <kjv_def>--Alpha.</kjv_def> Often used (usually
 <greek BETA="A)/N" unicode="??" translit="án" />, before a vowel) also in composition (as a contraction from <strongsref language="GREEK" strongs="427" />) in
 the sense of privation; so, in many words, beginning with this letter;
 occasionally in the sense of union (as a contraction of <strongsref language="GREEK" strongs="260" />).


</entry>
    <entry strongs="00002">
      <strongs>2</strongs>
      <greek BETA="*)AARW/N" unicode="?a???" translit="Aar?n" />
      <pronunciation strongs="ah-ar-ohn'" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="0175" />);</strongs_derivation>
      <strongs_def> Aaron, the brother of Moses</strongs_def>
      <kjv_def>:--Aaron.</kjv_def>
    </entry>
    <entry strongs="00003">
      <strongs>3</strongs>
      <greek BETA="*)ABADDW/N" unicode="?ßadd??" translit="Abadd?n" />
      <pronunciation strongs="ab-ad-dohn'" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="011" />);</strongs_derivation>
      <strongs_def> a destroying angel</strongs_def>
      <kjv_def>:--Abaddon.</kjv_def>
    </entry>
    <entry strongs="00004">
      <strongs>4</strongs>
      <greek BETA="A)BARH/S" unicode="?ßa???" translit="abar?s" />
      <pronunciation strongs="ab-ar-ace'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as a negative particle) and <strongsref language="GREEK" strongs="922" />;</strongs_derivation>
      <strongs_def> weightless, i.e.
 (figuratively) not burdensome</strongs_def>
      <kjv_def>:--from being burdensome.</kjv_def>
    </entry>
    <entry strongs="00005">
      <strongs>5</strongs>
      <greek BETA="*)ABBA=" unicode="?ßß?" translit="Abbâ" />
      <pronunciation strongs="ab-bah'" />
      <strongs_derivation>of Chaldee origin (<strongsref language="HEBREW" strongs="02" />);</strongs_derivation>
      <strongs_def> father as a vocative</strongs_def>
      <kjv_def>:--Abba.</kjv_def>
    </entry>
    <entry strongs="00006">
      <strongs>6</strongs>
      <greek BETA="*)/ABEL" unicode="?ße?" translit="Ábel" />
      <pronunciation strongs="ab'-el" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="01893" />);</strongs_derivation>
      <strongs_def> Abel, the son of Adam</strongs_def>
      <kjv_def>:--Abel.</kjv_def>
    </entry>
    <entry strongs="00007">
      <strongs>7</strongs>
      <greek BETA="*)ABIA/" unicode="?ß??" translit="Abiá" />
      <pronunciation strongs="ab-ee-ah'" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="029" />);</strongs_derivation>
      <strongs_def> Abijah, the name of two Israelites</strongs_def>
      <kjv_def>:--Abia.</kjv_def>
    </entry>
    <entry strongs="00008">
      <strongs>8</strongs>
      <greek BETA="*)ABIAQA/R" unicode="?ß?a???" translit="Abiathár" />
      <pronunciation strongs="ab-ee-ath'-ar" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="054" />);</strongs_derivation>
      <strongs_def> Abiathar, an Israelite</strongs_def>
      <kjv_def>:--Abiathar.</kjv_def>
    </entry>
    <entry strongs="00009">
      <strongs>9</strongs>
      <greek BETA="*)ABILHNH/" unicode="?ß?????" translit="Abilen?" />
      <pronunciation strongs="ab-ee-lay-nay'" />
      <strongs_derivation>of foreign origin (compare <strongsref language="HEBREW" strongs="058" />);</strongs_derivation>
      <strongs_def> Abilene, a region of Syria</strongs_def>
      <kjv_def>:--Abilene.</kjv_def>
    </entry>
    <entry strongs="00010">
      <strongs>10</strongs>
      <greek BETA="*)ABIOU/D" unicode="?ß???d" translit="Abioúd" />
      <pronunciation strongs="ab-ee-ood'" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="031" />);</strongs_derivation>
      <strongs_def> Abihud, an Israelite</strongs_def>
      <kjv_def>:--Abiud.</kjv_def>
    </entry>
    <entry strongs="00011">
      <strongs>11</strongs>
      <greek BETA="*)ABRAA/M" unicode="?ß?a?µ" translit="Abraám" />
      <pronunciation strongs="ab-rah-am'" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="085" />);</strongs_derivation>
      <strongs_def> Abraham, the Hebrew patriarch</strongs_def>
      <kjv_def>:--Abraham.</kjv_def> (In
 Acts 7:16 the text should probably read Jacob.)

</entry>
    <entry strongs="00012">
      <strongs>12</strongs>
      <greek BETA="A)/BUSSOS" unicode="?ß?ss??" translit="ábyssos" />
      <pronunciation strongs="ab'-us-sos" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as a negative particle) and a variation of <strongsref language="GREEK" strongs="1037" />;</strongs_derivation>
      <strongs_def> depthless,
 i.e. (specially) (infernal) "abyss"</strongs_def>
      <kjv_def>:--deep, (bottomless) pit.</kjv_def>
    </entry>
    <entry strongs="00013">
      <strongs>13</strongs>
      <greek BETA="*)/AGABOS" unicode="??aß??" translit="Ágabos" />
      <pronunciation strongs="ag'-ab-os" />
      <strongs_derivation>of Hebrew origin (compare <strongsref language="HEBREW" strongs="02285" />);</strongs_derivation>
      <strongs_def> Agabus, an Israelite</strongs_def>
      <kjv_def>:--Agabus.</kjv_def>
    </entry>
    <entry strongs="00014">
      <strongs>14</strongs>
      <greek BETA="A)GAQOERGE/W" unicode="??a??e????" translit="agathoergéo" />
      <pronunciation strongs="ag-ath-er-gheh'-o" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="18" /> and <strongsref language="GREEK" strongs="2041" />;</strongs_derivation>
      <strongs_def> to work good</strongs_def>
      <kjv_def>:--do good.</kjv_def>
    </entry>
    <entry strongs="00015">
      <strongs>15</strongs>
      <greek BETA="A)GAQOPOIE/W" unicode="??a??p????" translit="agathopoiéo" />
      <pronunciation strongs="ag-ath-op-oy-eh'-o" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="17" />;</strongs_derivation>
      <strongs_def> to be a well-doer (as a favor or a duty)</strongs_def>
      <kjv_def>:--(when) do good
 (well).</kjv_def>
    </entry>
    <entry strongs="00016">
      <strongs>16</strongs>
      <greek BETA="A)GAQOPOII/+A" unicode="??a??p???a" translit="agathopoi?a" />
      <pronunciation strongs="ag-ath-op-oy-ee'-ah" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="17" />;</strongs_derivation>
      <strongs_def> well-doing, i.e. virtue</strongs_def>
      <kjv_def>:--well-doing.</kjv_def>
    </entry>
    <entry strongs="00017">
      <strongs>17</strongs>
      <greek BETA="A)GAQOPOIO/S" unicode="??a??p????" translit="agathopoiós" />
      <pronunciation strongs="ag-ath-op-oy-os'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="18" /> and <strongsref language="GREEK" strongs="4160" />;</strongs_derivation>
      <strongs_def> a well-doer, i.e. virtuous</strongs_def>
      <kjv_def>:--them that do well.</kjv_def>
    </entry>
    <entry strongs="00018">
      <strongs>18</strongs>
      <greek BETA="A)GAQO/S" unicode="??a???" translit="agathós" />
      <pronunciation strongs="ag-ath-os'" />
      <strongs_derivation>a primary word;</strongs_derivation>
      <strongs_def> "good" (in any sense, often as noun)</strongs_def>
      <kjv_def>:--benefit,
 good(-s, things), well.</kjv_def> Compare <strongsref language="GREEK" strongs="2570" />.

</entry>
    <entry strongs="00019">
      <strongs>19</strongs>
      <greek BETA="A)GAQWSU/NH" unicode="??a??s???" translit="agathosýne" />
      <pronunciation strongs="ag-ath-o-soo'-nay" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="18" />;</strongs_derivation>
      <strongs_def> goodness, i.e. virtue or beneficence</strongs_def>
      <kjv_def>:--goodness.</kjv_def>
    </entry>
    <entry strongs="00020">
      <strongs>20</strongs>
      <greek BETA="A)GALLI/ASIS" unicode="??a???as??" translit="agallíasis" />
      <pronunciation strongs="ag-al-lee'-as-is" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="21" />;</strongs_derivation>
      <strongs_def> exultation; specially, welcome</strongs_def>
      <kjv_def>:--gladness, (exceeding) joy.</kjv_def>
    </entry>
    <entry strongs="00021">
      <strongs>21</strongs>
      <greek BETA="A)GALLIA/W" unicode="??a?????" translit="agalliáo" />
      <pronunciation strongs="ag-al-lee-ah'-o" />
      <strongs_derivation>from <greek BETA="A)/GAN" unicode="??a?" translit="ágan" /> (much) and <strongsref language="GREEK" strongs="242" />;</strongs_derivation>
      <strongs_def> properly, to jump for joy, i.e. exult</strongs_def>
      <kjv_def>:--be
 (exceeding) glad, with exceeding joy, rejoice (greatly).</kjv_def>
    </entry>
    <entry strongs="00022">
      <strongs>22</strongs>
      <greek BETA="A)/GAMOS" unicode="??aµ??" translit="ágamos" />
      <pronunciation strongs="ag'-am-os" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as a negative particle) and <strongsref language="GREEK" strongs="1062" />;</strongs_derivation>
      <strongs_def> unmarried</strongs_def>
      <kjv_def>:--unmarried.</kjv_def>
    </entry>
    <entry strongs="00023">
      <strongs>23</strongs>
      <greek BETA="A)GANAKTE/W" unicode="??a?a?t??" translit="aganaktéo" />
      <pronunciation strongs="ag-an-ak-teh'-o" />
      <strongs_derivation>from <greek BETA="A)/GAN" unicode="??a?" translit="ágan" /> (much) and <greek BETA="A)/XQOS" unicode="?????" translit="áchthos" /> (grief; akin to the base of <strongsref language="GREEK" strongs="43" />);</strongs_derivation>
      <strongs_def> to be
 greatly afflicted, i.e. (figuratively) indignant</strongs_def>
      <kjv_def>:--be much (sore)
 displeased, have (be moved with, with) indignation.</kjv_def>
    </entry>
    <entry strongs="00024">
      <strongs>24</strongs>
      <greek BETA="A)GANA/KTHSIS" unicode="??a???t?s??" translit="aganáktesis" />
      <pronunciation strongs="ag-an-ak'-tay-sis" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="23" />;</strongs_derivation>
      <strongs_def> indignation</strongs_def>
      <kjv_def>:--indignation.</kjv_def>
    </entry>
    <entry strongs="00025">
      <strongs>25</strongs>
      <greek BETA="A)GAPA/W" unicode="??ap??" translit="agapáo" />
      <pronunciation strongs="ag-ap-ah'-o" />
      <strongs_derivation>perhaps from <greek BETA="A)/GAN" unicode="??a?" translit="ágan" /> (much) [or compare <strongsref language="HEBREW" strongs="5689" />];</strongs_derivation>
      <strongs_def> to love (in a social or
 moral sense)</strongs_def>
      <kjv_def>:--(be-)love(-ed).</kjv_def> Compare <strongsref language="GREEK" strongs="5368" />.


</entry>
    <entry strongs="00026">
      <strongs>26</strongs>
      <greek BETA="A)GA/PH" unicode="???p?" translit="agápe" />
      <pronunciation strongs="ag-ah'-pay" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="25" />;</strongs_derivation>
      <strongs_def> love, i.e. affection or benevolence; specially (plural) a
 love-feast</strongs_def>
      <kjv_def>:--(feast of) charity(-ably), dear, love.</kjv_def>
    </entry>
    <entry strongs="00027">
      <strongs>27</strongs>
      <greek BETA="A)GAPHTO/S" unicode="??ap?t??" translit="agapetós" />
      <pronunciation strongs="ag-ap-ay-tos'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="25" />;</strongs_derivation>
      <strongs_def> beloved</strongs_def>
      <kjv_def>:--(dearly, well) beloved, dear.</kjv_def>
    </entry>
    <entry strongs="00028">
      <strongs>28</strongs>
      <greek BETA="*)/AGAR" unicode="??a?" translit="Ágar" />
      <pronunciation strongs="ag'-ar" />
      <strongs_derivation>of Hebrew origin (<strongsref language="HEBREW" strongs="01904" />);</strongs_derivation>
      <strongs_def> Hagar, the concubine of Abraham</strongs_def>
      <kjv_def>:--Hagar.</kjv_def>
    </entry>
    <entry strongs="00029">
      <strongs>29</strongs>
      <greek BETA="A)GGAREU/W" unicode="???a?e??" translit="angareúo" />
      <pronunciation strongs="ang-ar-yew'-o" />
      <strongs_derivation>of foreign origin (compare <strongsref language="HEBREW" strongs="0104" />);</strongs_derivation>
      <strongs_def> properly, to be a courier, i.e. (by
 implication) to press into public service</strongs_def>
      <kjv_def>:--compel (to go).</kjv_def>
    </entry>
    <entry strongs="00030">
      <strongs>30</strongs>
      <greek BETA="A)GGEI=ON" unicode="???e???" translit="angeîon" />
      <pronunciation strongs="ang-eye'-on" />
      <strongs_derivation>from <greek BETA="A)/GGOS" unicode="?????" translit="ángos" /> (a pail, perhaps as bent; compare the base of <strongsref language="GREEK" strongs="43" />);</strongs_derivation>
      <strongs_def> a
 receptacle</strongs_def>
      <kjv_def>:--vessel.</kjv_def>
    </entry>
    <entry strongs="00031">
      <strongs>31</strongs>
      <greek BETA="A)GGELI/A" unicode="???e??a" translit="angelía" />
      <pronunciation strongs="ang-el-ee'-ah" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="32" />;</strongs_derivation>
      <strongs_def> an announcement, i.e. (by implication) precept</strongs_def>
      <kjv_def>:--message.</kjv_def>
    </entry>
    <entry strongs="00032">
      <strongs>32</strongs>
      <greek BETA="A)/GGELOS" unicode="???e???" translit="ángelos" />
      <pronunciation strongs="ang'-el-os" />
      <strongs_derivation>from <greek BETA="A)GGE/LLW" unicode="???????" translit="angéllo" /> (probably derived from <strongsref language="GREEK" strongs="71" />;</strongs_derivation>
      <strongs_def> compare <strongsref language="GREEK" strongs="34" />) (to bring
 tidings); a messenger; especially an "angel"; by implication, a
 pastor</strongs_def>
      <kjv_def>:--angel, messenger.</kjv_def>
    </entry>
    <entry strongs="00033">
      <strongs>33</strongs>
      <greek BETA="A)/GE" unicode="??e" translit="áge" />
      <pronunciation strongs="ag'-eh" />
      <strongs_derivation>imperative of <strongsref language="GREEK" strongs="71" />;</strongs_derivation>
      <strongs_def> properly, lead, i.e. come on</strongs_def>
      <kjv_def>:--go to.</kjv_def>
    </entry>
    <entry strongs="00034">
      <strongs>34</strongs>
      <greek BETA="A)GE/LH" unicode="?????" translit="agéle" />
      <pronunciation strongs="ag-el'-ay" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="71" /> (compare <strongsref language="GREEK" strongs="32" />);</strongs_derivation>
      <strongs_def> a drove</strongs_def>
      <kjv_def>:--herd.</kjv_def>
    </entry>
    <entry strongs="00035">
      <strongs>35</strongs>
      <greek BETA="A)GENEALO/GHTOS" unicode="??e?ea????t??" translit="agenealógetos" />
      <pronunciation strongs="ag-en-eh-al-og'-ay-tos" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as negative particle) and <strongsref language="GREEK" strongs="1075" />;</strongs_derivation>
      <strongs_def> unregistered as to
 birth</strongs_def>
      <kjv_def>:--without descent.</kjv_def>
    </entry>
    <entry strongs="00036">
      <strongs>36</strongs>
      <greek BETA="A)GENH/S" unicode="??e???" translit="agen?s" />
      <pronunciation strongs="ag-en-ace'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as negative particle) and <strongsref language="GREEK" strongs="1085" />;</strongs_derivation>
      <strongs_def> properly, without kin, i.e.
 (of unknown descent, and by implication) ignoble</strongs_def>
      <kjv_def>:--base things.</kjv_def>
    </entry>
    <entry strongs="00037">
      <strongs>37</strongs>
      <greek BETA="A(GIA/ZW" unicode="??????" translit="hagiázo" />
      <pronunciation strongs="hag-ee-ad'-zo" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="40" />;</strongs_derivation>
      <strongs_def> to make holy, i.e. (ceremonially) purify or consecrate;
 (mentally) to venerate</strongs_def>
      <kjv_def>:--hallow, be holy, sanctify.</kjv_def>
    </entry>
    <entry strongs="00038">
      <strongs>38</strongs>
      <greek BETA="A(GIASMO/S" unicode="???asµ??" translit="hagiasmós" />
      <pronunciation strongs="hag-ee-as-mos'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="37" />;</strongs_derivation>
      <strongs_def> properly, purification, i.e. (the state) purity; concretely
 (by Hebraism) a purifier</strongs_def>
      <kjv_def>:--holiness, sanctification.</kjv_def>
    </entry>
    <entry strongs="00039">
      <strongs>39</strongs>
      <greek BETA="A(/GION" unicode="?????" translit="hágion" />
      <pronunciation strongs="hag'-ee-on" />
      <strongs_derivation>neuter of <strongsref language="GREEK" strongs="40" />;</strongs_derivation>
      <strongs_def> a sacred thing (i.e. spot)</strongs_def>
      <kjv_def>:--holiest (of all), holy
 place, sanctuary.</kjv_def>
    </entry>
    <entry strongs="00040">
      <strongs>40</strongs>
      <greek BETA="A(/GIOS" unicode="?????" translit="hágios" />
      <pronunciation strongs="hag'-ee-os" />
      <strongs_derivation>from <greek BETA="A(/GOS" unicode="????" translit="hágos" /> (an awful thing) (compare <strongsref language="GREEK" strongs="53" />, <strongsref language="GREEK" strongs="2282" />);</strongs_derivation>
      <strongs_def> sacred (physically,
 pure, morally blameless or religious, ceremonially,
 consecrated)</strongs_def>
      <kjv_def>:--(most) holy (one, thing), saint.</kjv_def>
    </entry>
    <entry strongs="00041">
      <strongs>41</strongs>
      <greek BETA="A(GIO/THS" unicode="????t??" translit="hagiótes" />
      <pronunciation strongs="hag-ee-ot'-ace" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="40" />;</strongs_derivation>
      <strongs_def> sanctity (i.e. properly, the state)</strongs_def>
      <kjv_def>:--holiness.</kjv_def>
    </entry>
    <entry strongs="00042">
      <strongs>42</strongs>
      <greek BETA="A(GIWSU/NH" unicode="????s???" translit="hagiosýne" />
      <pronunciation strongs="hag-ee-o-soo'-nay" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="40" />;</strongs_derivation>
      <strongs_def> sacredness (i.e. properly, the quality)</strongs_def>
      <kjv_def>:--holiness.</kjv_def>
    </entry>
    <entry strongs="00043">
      <strongs>43</strongs>
      <greek BETA="A)GKA/LH" unicode="??????" translit="ankále" />
      <pronunciation strongs="ang-kal'-ay" />
      <strongs_derivation>from <greek BETA="A)/GKOS" unicode="?????" translit="ánkos" /> (a bend, "ache");</strongs_derivation>
      <strongs_def> an arm (as curved)</strongs_def>
      <kjv_def>:--arm.</kjv_def>
    </entry>
    <entry strongs="00044">
      <strongs>44</strongs>
      <greek BETA="A)/GKISTRON" unicode="????st???" translit="ánkistron" />
      <pronunciation strongs="ang'-kis-tron" />
      <strongs_derivation>from the same as <strongsref language="GREEK" strongs="43" />;</strongs_derivation>
      <strongs_def> a hook (as bent)</strongs_def>
      <kjv_def>:--hook.</kjv_def>
    </entry>
    <entry strongs="00045">
      <strongs>45</strongs>
      <greek BETA="A)/GKURA" unicode="?????a" translit="ánkyra" />
      <pronunciation strongs="ang'-koo-rah" />
      <strongs_derivation>from the same as <strongsref language="GREEK" strongs="43" />;</strongs_derivation>
      <strongs_def> an "anchor" (as crooked)</strongs_def>
      <kjv_def>:--anchor.</kjv_def>
    </entry>
    <entry strongs="00046">
      <strongs>46</strongs>
      <greek BETA="A)/GNAFOS" unicode="???af??" translit="ágnaphos" />
      <pronunciation strongs="ag'-naf-os" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as a negative particle) and the same as <strongsref language="GREEK" strongs="1102" />;</strongs_derivation>
      <strongs_def> properly,
 unfulled, i.e. (by implication) new (cloth)</strongs_def>
      <kjv_def>:--new.</kjv_def>
    </entry>
    <entry strongs="00047">
      <strongs>47</strongs>
      <greek BETA="A(GNEI/A" unicode="???e?a" translit="hagneía" />
      <pronunciation strongs="hag-ni'-ah" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="53" />;</strongs_derivation>
      <strongs_def> cleanliness (the quality), i.e. (specially)
 chastity</strongs_def>
      <kjv_def>:--purity.</kjv_def>
    </entry>
    <entry strongs="00048">
      <strongs>48</strongs>
      <greek BETA="A(GNI/ZW" unicode="??????" translit="hagnízo" />
      <pronunciation strongs="hag-nid'-zo" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="53" />;</strongs_derivation>
      <strongs_def> to make clean, i.e. (figuratively) sanctify (ceremonially or
 morally)</strongs_def>
      <kjv_def>:--purify (self).</kjv_def>
    </entry>
    <entry strongs="00049">
      <strongs>49</strongs>
      <greek BETA="A(GNISMO/S" unicode="????sµ??" translit="hagnismós" />
      <pronunciation strongs="hag-nis-mos'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="48" />;</strongs_derivation>
      <strongs_def> a cleansing (the act), i.e. (ceremonially)
 lustration</strongs_def>
      <kjv_def>:--purification.</kjv_def>
    </entry>
    <entry strongs="00050">
      <strongs>50</strongs>
      <greek BETA="A)GNOE/W" unicode="??????" translit="agnoéo" />
      <pronunciation strongs="ag-no-eh'-o" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as a negative particle) and <strongsref language="GREEK" strongs="3539" />;</strongs_derivation>
      <strongs_def> not to know (through lack of
 information or intelligence); by implication, to ignore (through
 disinclination)</strongs_def>
      <kjv_def>:--(be) ignorant(-ly), not know, not understand,
 unknown.</kjv_def>
    </entry>
    <entry strongs="00051">
      <strongs>51</strongs>
      <greek BETA="A)GNO/HMA" unicode="?????µa" translit="agnóema" />
      <pronunciation strongs="ag-no'-ay-mah" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="50" />;</strongs_derivation>
      <strongs_def> a thing ignored, i.e. shortcoming</strongs_def>
      <kjv_def>:--error.</kjv_def>
    </entry>
    <entry strongs="00052">
      <strongs>52</strongs>
      <greek BETA="A)/GNOIA" unicode="?????a" translit="ágnoia" />
      <pronunciation strongs="ag'-noy-ah" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="50" />;</strongs_derivation>
      <strongs_def> ignorance (properly, the quality)</strongs_def>
      <kjv_def>:--ignorance.</kjv_def>
    </entry>
    <entry strongs="00053">
      <strongs>53</strongs>
      <greek BETA="A(GNO/S" unicode="?????" translit="hagnós" />
      <pronunciation strongs="hag-nos'" />
      <strongs_derivation>from the same as <strongsref language="GREEK" strongs="40" />;</strongs_derivation>
      <strongs_def> properly, clean, i.e. (figuratively) innocent,
 modest, perfect</strongs_def>
      <kjv_def>:--chaste, clean, pure.</kjv_def>
    </entry>
    <entry strongs="00054">
      <strongs>54</strongs>
      <greek BETA="A(GNO/THS" unicode="????t??" translit="hagnótes" />
      <pronunciation strongs="hag-not'-ace" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="53" />;</strongs_derivation>
      <strongs_def> cleanness (the state), i.e. (figuratively)
 blamelessness</strongs_def>
      <kjv_def>:--pureness.</kjv_def>
    </entry>
    <entry strongs="00055">
      <strongs>55</strongs>
      <greek BETA="A(GNW=S" unicode="?????" translit="hagnos" />
      <pronunciation strongs="hag-noce'" />
      <strongs_derivation>adverb from <strongsref language="GREEK" strongs="53" />;</strongs_derivation>
      <strongs_def> purely, i.e. honestly</strongs_def>
      <kjv_def>:--sincerely.</kjv_def>
    </entry>
    <entry strongs="00056">
      <strongs>56</strongs>
      <greek BETA="A)GNWSI/A" unicode="????s?a" translit="agnosía" />
      <pronunciation strongs="ag-no-see'-ah" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as negative particle) and <strongsref language="GREEK" strongs="1108" />;</strongs_derivation>
      <strongs_def> ignorance (properly, the
 state)</strongs_def>
      <kjv_def>:--ignorance, not the knowledge.</kjv_def>
    </entry>
    <entry strongs="00057">
      <strongs>57</strongs>
      <greek BETA="A)/GNWSTOS" unicode="????st??" translit="ágnostos" />
      <pronunciation strongs="ag'-noce-tos'" />
      <strongs_derivation>from <strongsref language="GREEK" strongs="1" /> (as negative particle) and <strongsref language="GREEK" strongs="1110" />;</strongs_derivation>
      <strongs_def> unknown</strongs_def>
      <kjv_def>:--unknown.</kjv_def>
    </entry>
    <entry strongs="00058">
      <strongs>58</strongs>
      <greek BETA="A)GORA/" unicode="?????" translit="agorá" />
      <pronunciation strongs="ag-or-ah'" />